DELETE FROM BILETY;
DELETE FROM ZAKUPY;
DELETE FROM REZERWACJE;
DELETE FROM KARNETY;
DELETE FROM TYPY_KARNETOW;
DELETE FROM PROMOCJE;
DELETE FROM KLIENCI;
DELETE FROM TYPY_KLIENTOW;
DELETE FROM CENY;
DELETE FROM IMPREZY;
DELETE FROM TYPY_IMPREZ;
DELETE FROM MIEJSCA;
DELETE FROM SEKTORY;
DELETE FROM STADIONY;
DELETE FROM TYPY_SEKTOROW;

/*drop view*/

drop sequence ID_TYPU_SEKTORA_seq;
drop sequence ID_STADIONU_seq;
drop sequence ID_SEKTORU_seq;
drop sequence ID_TYPU_IMPREZY_seq;
drop sequence ID_IMPREZY_seq;

DROP trigger INCREMENT_ID_TYPU_SEKTORA;
DROP trigger INCREMENT_ID_STADIONU;
DROP trigger INCREMENT_ID_SEKTORA;
DROP trigger INCREMENT_ID_TYPU_IMPREZY;
DROP trigger INCREMENT_ID_IMPREZY;

DROP procedure wstaw_do_typy_sektorow;
DROP procedure stworz_sektor_i_miejsca;
DROP procedure stworz_stadiony;
DROP procedure wstaw_do_typy_imprez;
DROP procedure stworz_imprezy;