SELECT * FROM typy_sektorow;
SELECT * FROM typy_klientow;
SELECT * FROM STADIONY ORDER BY ID_STADIONU;
SELECT * FROM SEKTORY ORDER BY ID_STADIONU;
SELECT COUNT(*) FROM STADIONY;
SELECT COUNT(*) FROM MIEJSCA WHERE id_sektora=6;
SELECT * FROM IMPREZY ORDER BY ID_STADIONU;
SELECT * FROM PROMOCJE;
SELECT * FROM Klienci ORDER BY PESEL;


DELETE FROM MIEJSCA;
DELETE FROM SEKTORY;
DELETE FROM STADIONY;
DELETE FROM IMPREZY;
DELETE FROM TYPY_SEKTOROW;
DELETE FROM TYPY_IMPREZ;
DELETE FROM typy_klientow;
DELETE FROM CENA;
DELETE FROM PROMOCJE;
DELETE FROM TYPY_KARNETOW;
DELETE FROM KLIENCI;

BEGIN
    WSTAW_DO_TYPY_SEKTOROW;
    WSTAW_DO_TYPY_IMPREZ;
    WSTAW_DO_TYPY_KLIENTOW;
    WSTAW_DO_STADIONY;
    WSTAW_DO_IMPREZY;
    WSTAW_DO_PROMOCJE;
    WSTAW_DO_TYPY_KARNETOW;
    WSTAW_DO_KLIENCI;
END;

BEGIN
    WSTAW_DO_KLIENCI;
END;
