SELECT * FROM typy_sektorow;
SELECT * FROM typy_klientow;
SELECT * FROM STADIONY ORDER BY ID_STADIONU;
SELECT * FROM SEKTORY ORDER BY ID_STADIONU;
SELECT COUNT(*) FROM STADIONY;
SELECT COUNT(*) FROM MIEJSCA WHERE id_sektora=6;
SELECT * FROM IMPREZY ORDER BY ID_STADIONU;
